### ISSUE TITLE
Plans to support management actions like Bpmn deployment?

### ISSUE THREAD

**Issue by StephenOTT** [zeebe-io/kafka-connect-zeebe#14]
Any plans or thoughts on supporting management actions like a Bpmn deployment through the connector?

**Comment by npepinpe** [comment]
Not at the moment. The main use case we saw here is to allow people to integrate Zeebe into an Kafka-backed architecture and orchestrate their processes with Zeebe with minimal changes to their existing services.

Having a sink connector which deploys workflows based on a Kafka record can be useful, but it's probably not business logic that already exists (i.e. passing BPMN definitions around with Kafka). So instead of building a new process to do that, I'd recommend users just deploy directly to Zeebe.

I could be wrong though and there might be people already passing around BPMN workflows using Kafka, and if so we can definitely revise this assumption; it shouldn't be too hard to create a sink connector to do this based on the existing one.

**Comment by berndruecker** [comment]
I agree with @npepinpe and would close the issue for the moment. Feel free to object :-)
