### ISSUE TITLE
Jobs buffer in Source is too big, leading to too much work getting acquired

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/kafka-connect-zeebe#27]
The current load test shows situations where there are too many jobs acquired and put into the in memory queue, leading to a massive number of timeouts.

**Comment by berndruecker** [comment]
Probable fix: https://github.com/zeebe-io/kafka-connect-zeebe/commit/965badc88ca78e3b66a7a03ed0e87b25b0cc16db

**Comment by npepinpe** [comment]
My only concern with this is that is that since we have two queues, the source task queue, and the job queue, the jobs in the job queue become stale (i.e. timeout) as they wait for the source task queue to be consumed. One possible way to avoid this is to check the job deadline before sending to Kafka and ignore jobs with deadlines in the past. This isn't 100% accurate but if we see we're feeding too many timed out jobs to Kafka then that would be a band-aid fix until we come up with something better.

**Comment by berndruecker** [comment]
With the latest fix from @menski the problem still persists, there are too many jobs in the queue and basically all get stale, so almost no progress is made any more, see e.g. 

![grafik](https://user-images.githubusercontent.com/1217596/68937276-62141f80-079c-11ea-9a0d-6b46e095236d.png)

While the proposal to remove timed out jobs would heal some symptoms, it does not solve the root problem, that is that we acquire jobs faster than we really execute them. Probably there is a way to do a proper throttling adjusting the rate of jobs acquired?

**Comment by npepinpe** [comment]
Would be a use case for the same back pressure library we used in the broker, but unfortunately that would require changes on the client side (`JobWorker`/`JobPoller`) in order to have dynamic polling rates.
